pipeline {
   agent any
   stages {
      stage('Build') {
         steps {
            echo 'Building...'
         }
      }
      stage('Test') {
         steps {
            echo 'Testing...'
         }
      }
      stage('Destribute') {
         steps {
            echo 'docker push...'
         }
      }
   }
}
